Repository pfnet/pfio, pull requests merged in 2019-12, with the labels that each got.

#82 Normalize input path in zip `stat`
  chainerio/containers/zip.py
  tests/container_tests/test_zip_container.py
Labels: cat:feature

#84 Normalize input path in zip `exists`
  chainerio/containers/zip.py
  tests/container_tests/test_zip_container.py
Labels: cat:feature

#85 Normalize input path in zip `open`
  chainerio/containers/zip.py
  tests/container_tests/test_zip_container.py
Labels: cat:feature

#90 Add persistence to cache.FileCache
  chainerio/cache/file_cache.py
  docs/source/reference.rst
  tests/cache_tests/test_file_cache.py
Labels: cat:feature

#91 Use keytab by environment variable
  chainerio/filesystems/hdfs.py
  docs/source/reference.rst
  setup.py
Labels: cat:feature

#83 Normalize input path in zip `isdir`
  chainerio/containers/zip.py
  tests/container_tests/test_zip_container.py
Labels: cat:feature

#95 Bugfix: remove out-of-date tests
  tests/filesystem_tests/test_hdfs_handler.py
Labels: cat:bug

#96 Move to krbticket 1.0.2
  chainerio/filesystems/hdfs.py
  setup.py
Labels: cat:enhancement

#97 Bugfix: get correct principal name when keytab is given
  chainerio/filesystems/hdfs.py
  docs/source/reference.rst
  tests/filesystem_tests/test_hdfs_handler.py
Labels: cat:bug

#103 Bugfix: test fails when KRB5_KTNAME is not set
  tests/filesystem_tests/test_hdfs_handler.py
Labels: cat:test
