Repository pfnet/pfio, pull requests merged in 2019-09, with the labels that each got.

#47 Add recursive to zip list
  chainerio/__init__.py
  chainerio/containers/zip.py
  chainerio/io.py
  tests/container_tests/test_zip_container.py
Labels: cat:feature

#44 Improve pickle performance on HDFS
  chainerio/filesystems/hdfs.py
Labels: cat:performance

#40 Nested Zip Support for Python<3.7
  chainerio/containers/zip.py
  tests/container_tests/test_zip_container.py
Labels: cat:feature, cat:test

#56 Fix an outdated example
  docs/source/design.rst
Labels: cat:document

#49 Add recursive support to list in hdfs
  chainerio/filesystems/hdfs.py
  tests/filesystem_tests/test_hdfs_handler.py
Labels: cat:feature

#57 Add recursive option to POSIX filesystem handler
  chainerio/__init__.py
  chainerio/filesystems/posix.py
  tests/filesystem_tests/test_posix_handler.py
  tests/test_context.py
Labels: cat:feature

#53 Add workaround for old python
  chainerio/__init__.py
  chainerio/_context.py
  chainerio/_typing.py
  chainerio/cache/__init__.py
  chainerio/container.py
  chainerio/containers/zip.py
  chainerio/filesystem.py
  chainerio/filesystems/hdfs.py
  chainerio/io.py
  setup.py
Labels: cat:feature

#58 Add doc strings to public API
  chainerio/__init__.py
  chainerio/io.py
  docs/source/reference.rst
Labels: cat:document
