Repository pfnet/pfio, pull requests merged in 2019-10, with the labels that each got.

#63 Remove mutable default argument
  chainerio/cache/file_cache.py
Labels: cat:bug

#64 Use TempDirectory for tests
  tests/container_tests/test_zip_container.py
  tests/filesystem_tests/test_posix_handler.py
  tests/test_context.py
Labels: cat:enhancement, cat:test

#65 Use `klist` to get the username from kerberos
  chainerio/filesystems/hdfs.py
  tests/filesystem_tests/test_hdfs_handler.py
Labels: cat:enhancement

#27 Change theme of docs
  .pfnci/test.sh
  docs/source/conf.py
  setup.py
Labels: cat:document

#68 Bugfix list zip
  chainerio/containers/zip.py
  tests/container_tests/test_zip_container.py
Labels: cat:bug

#75 Add Python 3.5.2 test to CI
  .pfnci/docker/Dockerfile
  .pfnci/docker/install.sh
  .pfnci/test.sh
Labels: cat:test

#73 Bugfix for recursive list with `path_or_prefix` in zip
  chainerio/containers/zip.py
  tests/container_tests/test_zip_container.py
Labels: cat:bug

#70 Support of directories without trailing slash in `stat` of zip
  chainerio/containers/zip.py
  tests/container_tests/test_zip_container.py
Labels: cat:feature

#71 Support of directories without trailing slash in `exists` of zip
  chainerio/containers/zip.py
  tests/container_tests/test_zip_container.py
Labels: cat:feature

#79 Avoid make_archive in the test_zip_container
  tests/container_tests/test_zip_container.py
Labels: cat:test

#69 Add tests of directories without trailing slash in `isdir` of zip
  tests/container_tests/test_zip_container.py
Labels: cat:test
