Repository pfnet/pfio, pull requests merged in 2021-12, with the labels that each got.

#236 Fix forkederror
  pfio/v2/fs.py
  pfio/v2/s3.py
  tests/v2_tests/test_s3.py
Labels: cat:bug

#240 Fix pathlib return value
  pfio/v2/pathlib.py
  tests/v2_tests/test_pathlib.py
Labels: cat:bug

#242 [Ready] Fix `_ObjectReader.seek(0, os.SEEK_END)` case
  pfio/v2/s3.py
  tests/v2_tests/test_s3.py
Labels: cat:bug

#246 Fix `pfio.v2.Hdfs.isdir` returns `True` to non-existent path
  pfio/v2/hdfs.py
  tests/v2_tests/test_hdfs.py
Labels: cat:bug

#248 Fix `S3.rename` didn't correctly remove the old file
  pfio/v2/s3.py
  tests/v2_tests/test_s3.py
Labels: cat:bug

#247 Buffered S3 reader
  pfio/v2/hdfs.py
  pfio/v2/local.py
  pfio/v2/s3.py
  pfio/v2/zip.py
  tests/v2_tests/test_s3.py
Labels: cat:enhancement

#249 Update Sphinx RTD theme
  docs/requirements.txt
Labels: cat:document
