Repository pfnet/pfio, pull requests merged in 2021-09, with the labels that each got.

#194 Fix off-by-one unit test failure
  pfio/v2/s3.py
Labels: cat:bug

#193 Fix BufferedIOBase requires readinto() implemented
  pfio/v2/s3.py
  tests/v2_tests/test_s3.py
Labels: cat:bug

#198 Fix listing root directory
  pfio/v2/s3.py
  tests/v2_tests/test_s3.py
Labels: cat:bug

#200 Fix autoclass in v2 API reference
  docs/source/v2.rst
Labels: cat:document

#199 Add pathlib-like API supporting glob and path concatination
  docs/source/v2.rst
  pfio/v2/__init__.py
  pfio/v2/pathlib.py
  pfio/v2/s3.py
  tests/v2_tests/test_pathlib.py
  tests/v2_tests/test_s3.py
Labels: cat:feature

#201 Add .parent, .name, .suffix
  pfio/v2/local.py
  pfio/v2/pathlib.py
  tests/v2_tests/test_pathlib.py
Labels: cat:feature

#202 V2doc
  docs/source/design.rst
  docs/source/index.rst
  docs/source/reference.rst
  docs/source/v2.rst
  pfio/v2/fs.py
  tests/v2_tests/test_pathlib.py
Labels: cat:document

#204 RTFD fix
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/api/.gitignore
  pfio/v2/hdfs.py
  setup.py
Labels: cat:document

#213 Fix bug in S3.list
  pfio/v2/s3.py
  tests/v2_tests/test_s3.py
Labels: cat:bug

#217 Make kwargs available in open_url too
  pfio/v2/fs.py
Labels: cat:enhancement

#212 Use relative path as an argument of boto3
  pfio/v2/s3.py
Labels: cat:code-fix
